### ISSUE TITLE
Include the .jar in the release

### ISSUE THREAD

**Issue by aalmada** [mbientlab/MetaWear-SDK-Android#11]
Can you please include the .jar in the release just like you used to do for 2.x? I'm developing using Xamarin and, just to compile this, I would have to install gigs of tools that I don't really use. Thanks.

**Comment by scaryghost** [comment]
Why would you recompile a project that is already publicly published?  Simply include Gradle or Apache Ivy in your build step and add a dependency to the MetaWear API.  API v3 depends on external libraries anyways so there's no point in manually retrieving those as well when Gradle and Apache Ivy will resolve those dependencies for you.
