### ISSUE TITLE
UNKNOWN_LOG_ENTRY

### ISSUE THREAD

**Issue by ValentinMerlet** [mbientlab/MetaWear-SDK-Android#14]
Hello !

I'm trying to log the accelerometer after killing my app but from the time I kill the app, the BLE Service is disconnected and when I try to get the logs from the sensor I have the following error : 
UNKNOWN_LOG_ENTRY from the errorHandler of the downloadAsync() method.

It's working fine when I start and stop logging inside my app without killing it.

Here the project https://github.com/umanit/metawear_sensor_logging_example/tree/master/app/src/main/java/capteur/umanit/fr/testcapteur I just created as an example. ConfigureActivity start the logging and GetLogActivity stop it, is there something I'm missing ? Again, those activities are achieving their job well if I don't kill the app.

**Comment by scaryghost** [comment]
If you kill your app, you've lost its entire state so of course you will get errors when trying to resume the app.  

Either save the object state before closing the app or use anonymous routes.  These are described in the documentation under *Serialization* and *Anonymous Routes*.
https://mbientlab.com/androiddocs/latest/advanced_features.html

**Comment by ValentinMerlet** [comment]
Thank for your answer,

Just to specify my question, what I'm trying to do is getting the logs from the sensor through a background Service (a JobScheduler technically). 

I thought that AnonymousRoutes was made only to manipulate sensors across multiple devices, I didn't notice that I can use them in my case. I'm gonna use serialization in last resort.

Thank for your assistance
