### ISSUE TITLE
Build Issue with SDK Version 3.4.0

### ISSUE THREAD

**Issue by dakshj** [mbientlab/MetaWear-SDK-Android#15]
The build was working fine with version 3.2.2 (didn't try any later releases between that and 3.4.0).

After updating to 3.4.0, I get the following build issue:

	Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\daksh\.gradle\caches\transforms-1\files-1.1\metawear-3.4.0.aar\96152564b9f60a709adaf03e19eb11a2\jars\classes.jar
	Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing com/mbientlab/metawear/impl/DebugImpl.class
	Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
	Error:Execution failed for task ':mobile:transformClassesWithDexBuilderForDebug'.
	> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\daksh\.gradle\caches\transforms-1\files-1.1\metawear-3.4.0.aar\96152564b9f60a709adaf03e19eb11a2\jars\classes.jar

I've tried a clean build -- does not work.

**Comment by scaryghost** [comment]
Read the README
https://github.com/mbientlab/MetaWear-SDK-Android#adding-compile-dependency
