### ISSUE TITLE
TUTORIAL PROBLEM Cannot Resolve symbol ´seviceBinder´

### ISSUE THREAD

**Issue by echiul** [mbientlab/MetaWear-SDK-Android#17]
Hi, When I was programming following the YouTube video, I had a problem I appeared: Cannot Resolve symbol ´seviceBinder´ and I do not know how to continue, in addition to the above I wanted to know if the same can be done but instead of accelerating with euler angles.
Please help me that I am stuck with this. Thank you very much in advance

**Comment by scaryghost** [comment]
This is not an SDK issue
