### ISSUE TITLE
RouteComponent conditional streaming

### ISSUE THREAD

**Issue by SarthakG16** [mbientlab/MetaWear-SDK-Android#19]
Hi, We are evaluating the Mbient Metatracker product. 
We want to stream from the sensor only if a certain condition is met. (Accelerometer)
For example, with the accelerometer, we want to stream the data if the RSS value of XYZ is > 1.4 and the z-axis value > 0.39.

 I have seen examples of filtering one of these values but I am not very sure how to filter in this situation. 

Wanted to check if we can do a custom filter on the RouteComponent or if there is any other way.

Also, is there a way to selectively stream the original xyz values, if this certain condition is met, as the RouteComponent progressively transform these values, and I am not sure how to stream the original ones.

Any direction is appreciated.

Thanks in advance

**Comment by lkasso** [comment]
Please direct these questions to our forum as they are not direct issues with our APIs.
