### ISSUE TITLE
ERROR: Failed to resolve: com.mbientlab:metawear:3.8.2

### ISSUE THREAD

**Issue by rpeterson2205** [mbientlab/MetaWear-SDK-Android#20]
I added ivy repo in project build.gradle. I added implementation for module build.gradle. I am using SDK 3.6.1. I cannot resolve the com.mbientlab:metawear:3.8.2 implementation. I tried it on work and personal computer so I am sure it is not a firewall issue. Please advise, thanks.

My module build.gradle is as follows:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.liminal"
        minSdkVersion 23
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    releaseImplementation 'androidx.appcompat:appcompat:1.4.0'
    implementation 'com.mbientlab:metawear:3.8.2'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}

**Comment by yd5618** [comment]
Hello, I have the same issue and would be grateful if anyone knew how to solve this.

**Comment by mattthebaker** [comment]
Version 3.9.0 is being released which fixes issues related to ivyrep, please give it a try shortly when it is up.

**Comment by tanmay-1srivastava** [comment]
Is version 3.9.0 up noww?
